// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"]!,
    // directUrl bypasses the connection pooler — required for Prisma Migrate
    // @ts-ignore — directUrl is valid at runtime but missing from Prisma's config type
    directUrl: process.env["DIRECT_URL"],
  },
});
